language: cpp
cache: 
  apt: true
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9

env:
  CC=gcc-4.9 
  CXX=g++-4.9
  BUILD_TYPE=Release

before_install:
 # - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
 - sudo apt-get update -qq
 - sudo apt-get install -qq build-essential cmake git-core
 # - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; fi
 - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; echo "g++ set"; fi
 # For boost: we will download and compile boost instead of using prebuild ones, 
 # since statically linking with boost requires the same tool chain, otherwise there will be link errors. 
 ### - sudo add-apt-repository -y ppa:boost-latest/ppa && sudo apt-get update -q && sudo apt-get install -y libboost1.55-all-dev
 - wget http://sourceforge.net/projects/boost/files/boost/1.61.0/boost_1_61_0.tar.bz2 --no-check-certificate
 - tar --bzip2 -xf boost_1_61_0.tar.bz2
 - cd boost_1_61_0
 - ./bootstrap.sh --help
 - "echo 'using gcc : 4.9 : /usr/bin/g++-4.9 ; ' >> tools/build/src/user-config.jam"
 - sudo ./bootstrap.sh --with-libraries="thread,date_time,filesystem,system,chrono,signals,serialization,iostreams,regex"
 - sudo ./b2 link=static threading=multi variant=release install
 ### - sudo ./b2 install | tail -n 50
 - cd ..


script: 
  - echo "running script!!!"
